defmodule Genswarms.Config.ExsWriter do
  @moduledoc """
  Emits an Elixir `.exs` swarm configuration from a `SwarmConfig` struct.

  Used by `swarm snapshot` to consolidate the in-memory state (seed ⊕ overlay)
  into a fresh declarative config. The output is formatted with
  `Code.format_string!/1`.

  Limitations:
    * Anonymous functions in the original config are not representable.
    * Dynamic expressions (e.g. `for i <- 1..N do ... end`) are expanded
      into their static result. Comments and original formatting are not
      preserved.
  """

  alias Genswarms.Config.SwarmConfig

  @spec to_exs_source(SwarmConfig.t()) :: String.t()
  def to_exs_source(%SwarmConfig{} = config) do
    header =
      "# Generated by Genswarms.Config.ExsWriter at #{DateTime.utc_now() |> DateTime.to_iso8601()}\n"

    body = """
    %{
      name: #{inspect(config.name)},
      agents: #{render_list(config.agents, &render_agent/1)},
      objects: #{render_list(config.objects || [], &render_object/1)},
      topology: #{render_list(config.topology, &render_edge/1)}
    }
    """

    formatted =
      try do
        body |> Code.format_string!() |> IO.iodata_to_binary()
      rescue
        _ -> body
      end

    header <> formatted <> "\n"
  end

  defp render_list([], _fun), do: "[]"

  defp render_list(items, fun) do
    rendered = items |> Enum.map(fun) |> Enum.join(",\n  ")
    "[\n  " <> rendered <> "\n]"
  end

  defp render_agent(spec) do
    fields =
      [
        name_field(spec),
        backend_field(spec),
        skills_field(spec),
        model_field(spec),
        endpoint_field(spec),
        presets_field(spec),
        config_field(spec)
      ]
      |> Enum.reject(&is_nil/1)
      |> Enum.join(", ")

    "%{" <> fields <> "}"
  end

  defp render_object(spec) do
    fields =
      [
        name_field(spec),
        handler_field(spec),
        backend_field(spec),
        config_field(spec)
      ]
      |> Enum.reject(&is_nil/1)
      |> Enum.join(", ")

    "%{" <> fields <> "}"
  end

  defp render_edge({from, to}), do: "{#{inspect(from)}, #{inspect(to)}}"

  # -- field helpers --

  defp name_field(spec), do: "name: #{inspect(Map.get(spec, :name))}"

  defp backend_field(spec) do
    case Map.get(spec, :backend) do
      nil -> nil
      b -> "backend: #{inspect(b)}"
    end
  end

  defp skills_field(spec) do
    case Map.get(spec, :skills, []) do
      [] -> nil
      s -> "skills: #{inspect(s)}"
    end
  end

  defp model_field(spec) do
    case Map.get(spec, :model) do
      nil -> nil
      m -> "model: #{inspect(m)}"
    end
  end

  defp endpoint_field(spec) do
    case Map.get(spec, :endpoint) do
      nil -> nil
      e -> "endpoint: #{inspect(e)}"
    end
  end

  defp presets_field(spec) do
    case Map.get(spec, :presets, []) do
      [] -> nil
      p -> "presets: #{inspect(p)}"
    end
  end

  defp config_field(spec) do
    case Map.get(spec, :config, %{}) do
      empty when empty == %{} -> nil
      c -> "config: #{inspect(c)}"
    end
  end

  defp handler_field(spec) do
    case Map.get(spec, :handler) do
      nil -> nil
      h -> "handler: #{inspect(h)}"
    end
  end
end
