defmodule Genswarms.Config.ExsWriter do
  @moduledoc """
  Emits an Elixir `.exs` swarm configuration from a `SwarmConfig` struct.

  Used by `swarm snapshot` to consolidate the in-memory state (seed ⊕ overlay)
  into a fresh declarative config. The output is formatted with
  `Code.format_string!/1`.

  Limitations:
    * Anonymous functions in the original config are not representable.
    * Dynamic expressions (e.g. `for i <- 1..N do ... end`) are expanded
      into their static result. Comments and original formatting are not
      preserved.
  """

  alias Genswarms.Config.SwarmConfig

  # Map keys whose name looks secret-bearing; their values are redacted before a
  # config/backend map is serialized, so a snapshot never persists secrets
  # (api_key, env passwords/tokens, …) in cleartext (CWE-312). Matches e.g.
  # api_key, SUBZEROCLAW_API_KEY, DB_PASSWORD, *_TOKEN, *secret*.
  @sensitive_key_regex ~r/(?:key|secret|token|password|passwd|credential)/i
  @redaction_placeholder "[REDACTED]"

  # Keys that match the regex but name a non-secret (a path/reference, not the
  # secret value itself) — must NOT be redacted or snapshot round-trip breaks
  # (e.g. an SSH agent's key_path is a filename, not a private key).
  @redaction_exceptions ~w(key_path)

  @spec to_exs_source(SwarmConfig.t()) :: String.t()
  def to_exs_source(%SwarmConfig{} = config) do
    header =
      "# Generated by Genswarms.Config.ExsWriter at #{DateTime.utc_now() |> DateTime.to_iso8601()}\n"

    body = """
    %{
      name: #{inspect(config.name)},
      agents: #{render_list(config.agents, &render_agent/1)},
      objects: #{render_list(config.objects || [], &render_object/1)},
      topology: #{render_list(config.topology, &render_edge/1)}
    }
    """

    formatted =
      try do
        body |> Code.format_string!() |> IO.iodata_to_binary()
      rescue
        _ -> body
      end

    header <> formatted <> "\n"
  end

  defp render_list([], _fun), do: "[]"

  defp render_list(items, fun) do
    rendered = items |> Enum.map(fun) |> Enum.join(",\n  ")
    "[\n  " <> rendered <> "\n]"
  end

  defp render_agent(spec) do
    fields =
      [
        name_field(spec),
        backend_field(spec),
        skills_field(spec),
        model_field(spec),
        endpoint_field(spec),
        presets_field(spec),
        config_field(spec)
      ]
      |> Enum.reject(&is_nil/1)
      |> Enum.join(", ")

    "%{" <> fields <> "}"
  end

  defp render_object(spec) do
    fields =
      [
        name_field(spec),
        handler_field(spec),
        backend_field(spec),
        config_field(spec)
      ]
      |> Enum.reject(&is_nil/1)
      |> Enum.join(", ")

    "%{" <> fields <> "}"
  end

  defp render_edge({from, to}), do: "{#{inspect(from)}, #{inspect(to)}}"

  # -- field helpers --

  defp name_field(spec), do: "name: #{inspect(Map.get(spec, :name))}"

  defp backend_field(spec) do
    case Map.get(spec, :backend) do
      nil -> nil
      b -> "backend: #{inspect(redact_secrets(b))}"
    end
  end

  defp skills_field(spec) do
    case Map.get(spec, :skills, []) do
      [] -> nil
      s -> "skills: #{inspect(s)}"
    end
  end

  defp model_field(spec) do
    case Map.get(spec, :model) do
      nil -> nil
      m -> "model: #{inspect(m)}"
    end
  end

  defp endpoint_field(spec) do
    case Map.get(spec, :endpoint) do
      nil -> nil
      e -> "endpoint: #{inspect(e)}"
    end
  end

  defp presets_field(spec) do
    case Map.get(spec, :presets, []) do
      [] -> nil
      p -> "presets: #{inspect(p)}"
    end
  end

  defp config_field(spec) do
    case Map.get(spec, :config, %{}) do
      empty when empty == %{} -> nil
      c -> "config: #{inspect(redact_secrets(c))}"
    end
  end

  defp handler_field(spec) do
    case Map.get(spec, :handler) do
      nil -> nil
      h -> "handler: #{inspect(h)}"
    end
  end

  # Recursively replace the value of any map key whose name looks sensitive with
  # a placeholder. Walks nested maps/lists/tuples so secrets inside backend opts
  # and extra_env are caught too. The snapshot deliberately does not round-trip
  # the real secret — the operator restores it via env (e.g. SUBZEROCLAW_API_KEY).
  defp redact_secrets(map) when is_map(map) do
    Map.new(map, fn {k, v} ->
      if sensitive_key?(k), do: {k, @redaction_placeholder}, else: {k, redact_secrets(v)}
    end)
  end

  defp redact_secrets(list) when is_list(list), do: Enum.map(list, &redact_secrets/1)

  defp redact_secrets(tuple) when is_tuple(tuple) do
    tuple |> Tuple.to_list() |> Enum.map(&redact_secrets/1) |> List.to_tuple()
  end

  defp redact_secrets(other), do: other

  defp sensitive_key?(key) do
    str = to_string(key)
    str not in @redaction_exceptions and String.match?(str, @sensitive_key_regex)
  end
end
